server:
  port: 8761
spring:
  application:
    name: eros-eureka
eureka:
  instance:
    hostname: 127.0.0.1
  server:
    renewal-percent-threshold: 0.85
  client:
    register-with-eureka: false # 表示是否注册自身到eureka服务器
    fetch-registry: false # 是否从eureka上获取注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
