server:
  port: 9990
  undertow:
    accesslog:
      enabled: false
    io-threads: 10
    worker-threads: 100
spring:
  application:
    name: uranus-interface-normal
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    show-sql: true
  jackson:
    time-zone: CTT #Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  ###### spring datasource ######
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: cloud-dev
    password: cloud-dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
  ###### spring redis ######
  redis:
    database: 12
    host: 10.39.48.16
    port: 6379
    password: FNpro0426
    timeout: 60000
    lettuce:
      pool:
      max-active: 1024
      max-idle: 100
      max-wait: 30
      min-idle: 20
executor:
  scheduler:
    pool-size: 120
    expire-after: 60000
    registry-key: SCHEDULER_LOCK
  task:
    max-pool-size: 120
    core-pool-size: 10
    queue-capacity: 50

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


