server:
  port: 9990
  undertow:
    accesslog:
      enabled: false
    io-threads: 10
    worker-threads: 100
spring:
  application:
    name: uranus-interface-normal
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
    show-sql: true
  jackson:
    time-zone: CTT #Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  ###### spring datasource ######
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud-dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: cloud-dev
    password: cloud-dev
    type: com.zaxxer.hikari.HikariDataSource # 使用druid数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
  ###### spring redis ######
  redis:
    database: 12
    host: 10.39.48.16
    port: 6379
    password: FNpro0426


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka


